import unneeded.pid as pid

dict = pid.PID_DICT


pids = {
    '01': 'Monitor status since DTCs cleared',
    '02': 'DTC that caused required freeze frame data storage',
    '03': 'Fuel system status',
    '04': 'Calculated load value',
    '05': 'Engine coolant temperature',
    '06': 'Short term fuel trim (banks 1 and 3)',
    '07': 'Long term fuel trim (banks 1 and 3)',
    '08': 'Short term fuel trim (banks 2 and 4)',
    '09': 'Long term fuel trim (banks 2 and 4)',
    '0A': 'Fuel rail pressure (gauge)',
    '0B': 'Intake manifold absolute pressure',
    '0C': 'Engine RPM',
    '0D': 'Vehicle speed',
    '0E': 'Ignition timing advance for #1 cylinder',
    '0F': 'Intake air temperature',
    '10': 'Air flow rate from mass air flow sensor',
    '11': 'Absolute throttle position',
    '12': 'Commanded secondary air status',
    '13': 'Location of oxygen sensors (up to 2 banks)',
    '14': 'Oxygen sensor (narrowband) bank 1 sensor 1',
    '15': 'Oxygen sensor (narrowband) bank 1 sensor 2',
    '16': 'Oxygen sensor (narrowband) bank 1 sensor 3',
    '17': 'Oxygen sensor (narrowband) bank 1 sensor 4',
    '18': 'Oxygen sensor (narrowband) bank 2 sensor 1',
    '19': 'Oxygen sensor (narrowband) bank 2 sensor 2',
    '1A': 'Oxygen sensor (narrowband) bank 2 sensor 3',
    '1B': 'Oxygen sensor (narrowband) bank 2 sensor 4',
    '1C': 'OBD requirements to which vehicle or engine is certified',
    '1D': 'Location of oxygen sensors (up to 4 banks)',
    '1E': 'Auxiliary input status',
    '1F': 'Time since engine start',
    '20': 'PID support status for PIDs $21-$40',
    '21': 'Distance traveled while MIL is activated',
    '22': 'Fuel rail pressure relative to manifold vacuum',
    '23': 'Fuel rail pressure',
    '24': 'Oxygen sensor (wideband) bank 1 sensor 1',
    '25': 'Oxygen sensor (wideband) bank 1 sensor 2',
    '26': 'Oxygen sensor (wideband) bank 1 sensor 3',
    '27': 'Oxygen sensor (wideband) bank 1 sensor 4',
    '28': 'Oxygen sensor (wideband) bank 2 sensor 1',
    '29': 'Oxygen sensor (wideband) bank 2 sensor 2',
    '2A': 'Oxygen sensor (wideband) bank 2 sensor 3',
    '2B': 'Oxygen sensor (wideband) bank 2 sensor 4',
    '2C': 'Commanded EGR',
    '2D': 'EGR Error',
    '2E': 'Commanded Evaporative Purge',
    '2F': 'Fuel Level Input',
    '30': 'Number of warm-ups since DTCs cleared',
    '31': 'Distance traveled since DTCs cleared',
    '32': 'Evap System Vapor Pressure',
    '33': 'Barometric Pressure',
    '34': 'Oxygen sensor (wideband) bank 1 sensor 1',
    '35': 'Oxygen sensor (wideband) bank 1 sensor 2',
    '36': 'Oxygen sensor (wideband) bank 1 sensor 3',
    '37': 'Oxygen sensor (wideband) bank 1 sensor 4',
    '38': 'Oxygen sensor (wideband) bank 2 sensor 1',
    '39': 'Oxygen sensor (wideband) bank 2 sensor 2',
    '3A': 'Oxygen sensor (wideband) bank 2 sensor 3',
    '3B': 'Oxygen sensor (wideband) bank 2 sensor 4',
    '3C': 'Catalyst Temperature Bank 1, Sensor 1',
    '3D': 'Catalyst Temperature Bank 2, Sensor 1',
    '3E': 'Catalyst Temperature Bank 1, Sensor 2',
    '3F': 'Catalyst Temperature Bank 2, Sensor 2',
    '40': 'PID support status for PIDs $41-$60',
    '41': 'Monitor status this driving cycle',
    '42': 'Control module voltage',
    '43': 'Absolute Load Value',
    '44': 'Fuel/Air Commanded Equivalence Ratio',
    '45': 'Relative Throttle Position',
    '46': 'Ambient air temperature',
    '47': 'Absolute Throttle Position B',
    '48': 'Absolute Throttle Position C',
    '49': 'Absolute Throttle Position D',
    '4A': 'Absolute Throttle Position E',
    '4B': 'Absolute Throttle Position F',
    '4C': 'Commanded Throttle Actuator Control',
    '4D': 'Engine run time while MIL is activated',
    '4E': 'Engine run time since DTCs cleared',
    '4F': 'External Test Equipment Configuration Information #1',
    '50': 'External Test Equipment Configuration Information #2',
    '51': 'Type of fuel currently being utilized by the vehicle',
    '52': 'Alcohol Fuel Percentage',
    '53': 'Absolute Evap System Vapor Pressure',
    '54': 'Evap System Vapor Pressure',
    '55': 'Short Term Secondary O2 Sensor Fuel Trim Banks 1 and 3',
    '56': 'Long Term Secondary O2 Sensor Fuel Trim Banks 1 and 3',
    '57': 'Short Term Secondary O2 Sensor Fuel Trim Banks 2 and 4',
    '58': 'Long Term Secondary O2 Sensor Fuel Trim Banks 2 and 4',
    '59': 'Fuel Rail Pressure (absolute)',
    '5A': 'Relative Accelerator Pedal Position',
    '5B': 'Hybrid/EV Battery Pack Remaining Charge',
    '5C': 'Engine Oil Temperature',
    '5D': 'Fuel Injection Timing',
    '5E': 'Engine Fuel Rate',
    '5F': 'Emission requirements to which vehicle is designed',
    '60': 'PID support status for PIDs $61-$80',
    '61': "Driver's Demand Engine - Percent Torque",
    '62': 'Actual Engine - Percent Torque',
    '63': 'Engine Reference Torque',
    '64': 'Engine Percent Torque Data',
    '65': 'Auxiliary Inputs / Outputs',
    '66': 'Mass Air Flow Sensor',
    '67': 'Engine Coolant Temperature',
    '68': 'Intake Air Temperature Sensor',
    '69': 'Commanded EGR and EGR Error',
    '6A': 'Commanded Diesel Intake Air Flow Control and Relative Intake Air Flow Position',
    '6B': 'Exhaust Gas Recirculation Temperature',
    '6C': 'Commanded Throttle Actuator Control and Relative Throttle Position',
    '6D': 'Fuel Pressure Control System',
    '6E': 'Injection Pressure Control System',
    '6F': 'Turbocharger Compressor Inlet Pressure',
    '70': 'Boost Pressure Control',
    '71': 'Variable Geometry Turbo (VGT) Control',
    '72': 'Wastegate Control',
    '73': 'Exhaust Pressure',
    '74': 'Turbocharger RPM',
    '75': 'Turbocharger A Temperature',
    '76': 'Turbocharger B Temperature',
    '77': 'Charge Air Cooler Temperature (CACT)',
    '78': 'Exhaust Gas Temperature (EGT) Bank 1',
    '79': 'Exhaust Gas Temperature (EGT) Bank 2',
    '7A': 'Diesel Particulate Filter (DPF) Bank 1',
    '7B': 'Diesel Particulate Filter (DPF) Bank 2',
    '7C': 'Diesel Particulate Filter (DPF) Temperature',
    '7D': 'NOx NTE control area status',
    '7E': 'PM NTE control area status',
    '7F': 'Engine Run Time',
    '80': 'PID support status for PIDs $81-$A0',
    '81': 'Engine Run Time for AECD #1 - #5',
    '82': 'Engine Run Time for AECD #6 - #10',
    '83': 'NOx Sensor',
    '84': 'Intake Manifold Surface Temperature',
    '85': 'NOx Control System',
    '86': 'Particulate Matter (PM) Sensor',
    '87': 'Intake Manifold Absolute Pressure',
    '88': 'SCR inducement system',
    '89': 'Engine Run Time for AECD #11 - #15',
    '8A': 'Engine Run Time for AECD #16 - #20',
    '8B': 'Diesel Aftertreatment Status',
    '8C': 'O2 Sensor (Wide Range)',
    '8D': 'Absolute Throttle Position G',
    '8E': 'Engine Friction - Percent Torque',
    '8F': 'Particulate Matter (PM) Sensor Output',
    '90': 'WWH-OBD Vehicle OBD System Information',
    '91': 'WWH-OBD ECU OBD System Information',
    '92': 'Fuel System Control Status (Compression Ignition)',
    '93': 'WWH-OBD Vehicle OBD Counters',
    '94': 'NOx control - driver inducement system status and counters',
    '95': 'Reserved',
    '96': 'Reserved',
    '97': 'Reserved',
    '98': 'Exhaust Gas Temperature (EGT) Bank 1',
    '99': 'Exhaust Gas Temperature (EGT) Bank 2',
    '9A': 'Reserved',
    '9B': 'Reserved',
    '9C': 'O2 Sensor (Wide Range)',
    '9D': 'Reserved',
    '9E': 'Reserved',
    '9F': 'Reserved',
}


for pid in pids.keys() :
    try:
        
        if dict["01"+pid]:

            p = dict["01"+pid]
            dict["01"+pid]['name'] = pids[pid]  
    except:
        print("Not found")
    

print(dict)

with open("newPID.py", "w") as f:
    f.write(dict.__str__())